# docker-compose.portainer.yml
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "8000:8000"
      - "9443:9443"
    environment:
      - TZ=America/Caracas  # Establece la zona horaria
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - development-network

  mysql-server:
    image: mysql:8.0
    container_name: dev-mysql
    restart: always
    ports:
      - 25060:3306
    environment:
      - MYSQL_ROOT_PASSWORD=26QCDexGh7
      - TZ=America/Caracas
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - development-network

  postgres-server:
    image: postgres:16
    container_name: dev-postgres
    restart: always
    ports:
      - 25061:5432
    environment:
      - POSTGRES_PASSWORD=26QCDexGh7
      - TZ=America/Caracas
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - development-network

  redis-server:
    image: redis
    container_name: dev-redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      - TZ=America/Caracas
      - REDIS_PASSWORD=FeSBbMIywltp0LMdQcT9nStuZUosLxUVqwX2dJInvfc=
    volumes:
      - redis_data:/data
    command: [ "redis-server", "--requirepass", "FeSBbMIywltp0LMdQcT9nStuZUosLxUVqwX2dJInvfc=", "--appendonly", "yes", "--save", "60", "1" ]
    networks:
      - development-network

volumes:
  portainer_data:
  mysql_data:
  postgres-data:
  redis_data:

networks:
  development-network:
    driver: bridge