services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - TZ=${TZ}

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

    networks:
      - staging-network

networks:
  staging-network:
    name: staging-network
    driver: bridge

volumes:
  rabbitmq_data:
    name: rabbitmq_data